### ISSUE TITLE
Plugin doesnt appear in game

### ISSUE THREAD

**Issue by boomam** [Sadret/openrct2-soft-guest-cap-calculator#2]
Hi,
Installed the latest version of the plugin as of now (v2.0.0), latest OpenRCT2 as well - plugin does not appear in maps menu as mentioned in documentation.  
Are additional steps required for usage, or is this a known issue?

Thanks!

**Comment by Sadret** [comment]
Hi, please make sure that you use a recent _development_ version and not the latest _release_ version.

**Comment by boomam** [comment]
Hi,
Thanks for the quick response, I was just about to start listing the other plugins in use.
Flipping to the non-latest version appears to have fixed the issue.

To help with others, may i suggest depreciating in some manner the v2/latest release you have listed so its clear it does not work?
You currently have listed as the install guide:
_Go to the releases page and download the soft-guest-cap-calculator-2.0.0.js file from the latest release_
...however if it doesnt work yet, could be worth correcting the wording?

Or making the differentiation for the version requirements to clear it up for any newcomers?

Thanks!

**Comment by Sadret** [comment]
Immediately before what you have cited:
_Make sure that your OpenRCT2 version is up-to-date. You need at least version 0.3.4 (as of June 2021: not yet released) or a recent development version._

**Comment by Sadret** [comment]
And on the release page:
_This release needs at least OpenRCT v3.4.0 or a recent development version. If you are on OpenRCT2 v0.3.3 and you cannot or do not want to upgrade, consider using the previous release, which works with v0.3.3._

**Comment by boomam** [comment]
I would contest that its not 100% clear - most people will just download the latest available 'stable'.
If you add clearer text for differentiation of version, assuming the minimum version doesn't drop in the next few weeks, then it would clear up the issue for others too, and better advise them to use the older version in the interim.

**Comment by Sadret** [comment]
I added as much clarification as is reasonable.
