### ISSUE TITLE
Starting blank new scenarios results in wrong soft guest cap message

### ISSUE THREAD

**Issue by SpartanFrederic104** [Sadret/openrct2-soft-guest-cap-calculator#4]
![Vertiginous Views 2022-07-06 21-24-31](https://user-images.githubusercontent.com/61885939/177797794-7f819f29-4a89-4f5c-aa03-7d702ffc9e7a.png)
This issue commonly occurs when I create a new scenario via the Scenario Editor and then start it up. Even though the park starts with no rides or stalls, the soft guest cap calculator plug-in wrongly assumes that there are rides built and opened in the park, thus giving a message of the soft guest cap having been increased to something like 895 despite that no rides are opened, which should result in a soft guest cap of 0.

I took this screenshot while creating the Vertiginous Views scenario. The Hybrid Coaster present in this screenshot will contribute 120 to the soft guest cap when opened, but I was still constructing it at the time of taking this screenshot.

**Comment by Andrew7811** [comment]
I am running into similar issues when creating new parks when harder guest generation is enabled. For example, the plugin reports that my 6 excitement 600 meter long giga coaster contributes 240 guests to the soft guest count when it is in test mode. When the coaster opens, the plugin will report the coaster contributes 360 guests to the soft guest count.

**Comment by Sadret** [comment]
I'll try to look into it soon. Can you two give me exact steps to reproduce?

**Comment by Andrew7811** [comment]
Reproduction Steps for the varying reported soft guest caps when harder guest generation is enabled:

1. Start a new game of Alpine Adventures. The chairlift you start with contributes 55 to the soft guest count.
2. Increase your loan to $20,000 and build the Woodchip wooden coaster prebuild in the park.
3. Put Woodchip in Test Mode. After the stats are done calculating, a notification is sent saying the soft guest count is 265.
4. Open Woodchip. You should receive a notification saying the soft guest count is 370.

I am able to reproduce this bug in both the current OpenRCT2 release (V0.4.1) and the latest develop build the OpenRCT2 installer gave me at the time of me writing this post.

**Comment by SpartanFrederic104** [comment]
For the soft guest cap being wrong when you start a new scenario:

1. Create a new scenario in the scenario editor
2. Start a new game in that newly created scenario
3. If done correctly the soft guest count notification should be wrong despite no rides or stalls being present in the park

I can reproduce this in both the current v0.4.1 release and the v0.4.1-154-g980e3cb (https://github.com/OpenRCT2/OpenRCT2/commit/980e3cbc4ce5834036d1c9b03fe81765b0ca0e1b on develop) builds.

**Comment by Sadret** [comment]
I'll close this issue as both problems are with OpenRCT2 and not with the plugin. In theory I could adapt the plugin to work around the bugs, but I would rather wait until OpenRCT2 fixes the issues.
