### ISSUE TITLE
With increase/decrease messages disabled, pressing C does not send a notification

### ISSUE THREAD

**Issue by sudofox** [Sadret/openrct2-soft-guest-cap-calculator#5]
Sometimes I just want to be able to trigger a notification without having constant updates (especially when fast-forwarding). It seems that with the two notif categories turned off, pressing C doesn't trigger a notification at all.

**Comment by SpartanFrederic104** [comment]
This happens to me when I play for long enough, usually when I start another new game in a different scenario after starting one.
